services:
  anmal:
    build:
      context: .
      args:
        REACT_APP_RECAPTCHA_PUBLIC_KEY: bingus
      target: dev
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DATABASE_URL: postgres://jml:jml@localhost:5432/jml
      LOGIN_API_KEY: aaaa
      OIDC_CLIENT_ID: client-id
      OIDC_CLIENT_SECRET: client-secret
      OIDC_ISSUER: http://localhost:7003
      REDIRECT_URL: http://localhost:8080/oidc/callback
      SESSION_SECRET: big_random_grej
      SPAM_API_KEY: aaaa
      RECAPTCHA_SECRET_KEY: yeet
      SPAM_API_URL: https://spam.datasektionen.se/api
      GOOGLE_RECAPTCHA_API_URL: https://www.google.com/recaptcha/api/siteverify
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json
    network_mode: "host"
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=jml
      - POSTGRES_USER=jml
      - POSTGRES_DB=jml
    healthcheck:
      test:
        - "CMD-SHELL"
        - "sh -c 'pg_isready -d jml -U jml'"
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s
  nyckeln:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan:latest
    configs:
      - source: nyckeln.yaml
        target: /config.yaml
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004

configs:
  nyckeln.yaml:
    content: |
      clients:
        - id: "client-id"
          secret: "client-secret"
          redirect_uris:
            - "http://localhost:8080/oidc/callback"

      users:
        - ug_kth_id: some-id
          kth_id: turetek
          email: turetek@kth.se
          first_name: Ture
          family_name: Teknolog
          year_tag: D-00
          hive_tags:
            - id: personal_email
              content: turetek@gmail.com
        - ug_kth_id: schmunguss
          kth_id: schmunguss
          email: schmunguss@kth.se
          first_name: Schmun
          family_name: Guss
          year_tag: D-69

      hive:
        groups:
          - name: Jämlikhets-, Mångfalds- och Likabehandlingsansvarig
            id: jmla
            domain: example.com
            members:
              - turetek
            tags:
              - id: mandate
            permissions:
              - id: admin
                scope: null
  nginx.conf:
    content: |
      server {
        listen       8000;
        server_name  localhost;

        access_log  /dev/null  main;

        location /api {
          proxy_pass http://anmal:8001/api;
        }

        location / {
          proxy_pass http://anmal:8002;
        }
      }
